module(name = "wfa-containers")

# Bazel Central Registry deps.
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_distroless", version = "0.8.0")

# WFA registry deps.
bazel_dep(name = "rules_cue", version = "0.4.1", repo_name = "wfa_rules_cue")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# bazel
http_file(
    name = "bazelisk",
    downloaded_file_path = "bazelisk",
    executable = True,
    sha256 = "d28b588ac0916abd6bf02defb5433f6eddf7cba35ffa808eabb65a44aab226f7",
    urls = ["https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"],
)

# kubectl
http_file(
    name = "kubectl",
    downloaded_file_path = "kubectl",
    executable = True,
    sha256 = "7816d067740f47f949be826ac76943167b7b3a38c4f0c18b902fffa8779a5afa",
    urls = ["https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl"],
)

_XZ_DEB_BUILD = """\
genrule(
    name = "decompress_data",
    srcs = ["data.tar.xz"],
    outs = ["layer.tar"],
    cmd = "xz --decompress --stdout $< >$@",
)

alias(
    name = "layer",
    actual = ":layer.tar",
    visibility = ["//visibility:public"],
)
"""

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# gcloud
http_archive(
    name = "google_cloud_cli",
    build_file_content = _XZ_DEB_BUILD,
    sha256 = "568366af2c266f73f44b302536eb2b7e143d67d783aaf0f89452dbd8ca805410",
    urls = [
        "https://packages.cloud.google.com/apt/pool/cloud-sdk/google-cloud-cli_455.0.0-0_all_2ea45cb35154dc574cecab4cf43dbfdb.deb",
    ],
)

# jdk, mirroring what distroless uses for debian13 https://github.com/GoogleContainerTools/distroless/blob/8a165b855b6d14366edb293e74ade0d7bace2f57/private/repos/deb/trixie_adoptium.lock.json#L18
http_archive(
    name = "temurin_17_jdk",
    build_file_content = _XZ_DEB_BUILD,
    sha256 = "ce5e529f453ae11e41ddb3ae25979df491634fd4d3f4ed5fed44db1d13ca502f",
    urls = [
        "https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.18.0.0+8-1_amd64.deb",
    ],
)

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "debian_trixie_slim",
    digest = "sha256:5fb70129351edec3723d13f427400ecae3f13b83750e23ad47c46721effcf2db",
    image = "docker.io/library/debian",
)
use_repo(oci, "debian_trixie_slim")

apt = use_extension(
    "@rules_distroless//apt:extensions.bzl",
    "apt",
)

apt.install(
    name = "debian_packages",
    manifest = "//:packages.yaml",
    lock = "//:packages.lock.json",
    mergedusr = True,
)

use_repo(apt, "debian_packages")